apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-local
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi  # GitLab needs more storage than N8N
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/k8s-data/gitlab
    type: DirectoryOrCreate



